language: go

go:
  - "1.11"
  - tip

install: 
- go get golang.org/x/crypto/curve25519
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls 

script:
- go get github.com/ConnorJarvis/TorMessage
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)