language: go

go:
  - "1.11"
  - tip

install: 
- go get golang.org/x/crypto/curve25519
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls 
- go get github.com/firstrow/tcp_server

script:
- go get github.com/ConnorJarvis/TorMessage
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $repo_token